// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type MessageRepository interface {
	Create(ctx context.Context, userID uuid.UUID, message *models.Message) (*models.Message, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.Message, error)
	
	FindByID(ctx context.Context, userID uuid.UUID, messageID uuid.UUID) (*models.Message, error)
	Update(ctx context.Context, userID uuid.UUID, message *models.Message) (*models.Message, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, messageID uuid.UUID, message *models.Message, fields *MessageUpdateFields) (*models.Message, error)
	Delete(ctx context.Context, userID uuid.UUID, messageID uuid.UUID) error
}

type MessageUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewMessageUpdateFields() *MessageUpdateFields {
	return &MessageUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *MessageUpdateFields) ConversationID() *MessageUpdateFields {
	return f.add("conversation_id")
}

func (f *MessageUpdateFields) Role() *MessageUpdateFields {
	return f.add("role")
}

func (f *MessageUpdateFields) SenderPersonID() *MessageUpdateFields {
	return f.add("sender_person_id")
}

func (f *MessageUpdateFields) SenderUserID() *MessageUpdateFields {
	return f.add("sender_user_id")
}

func (f *MessageUpdateFields) MetaData() *MessageUpdateFields {
	return f.add("meta_data")
}

func (f *MessageUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *MessageUpdateFields) add(column string) *MessageUpdateFields {
	if f == nil {
		f = NewMessageUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
