// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type MessageFeedbackRepository interface {
	Create(ctx context.Context, userID uuid.UUID, messageFeedback *models.MessageFeedback) (*models.MessageFeedback, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.MessageFeedback, error)
	ListByConversationID(ctx context.Context, userID uuid.UUID, conversationID uuid.UUID) ([]*models.MessageFeedback, error)
	FindByID(ctx context.Context, userID uuid.UUID, messageFeedbackID uuid.UUID) (*models.MessageFeedback, error)
	Update(ctx context.Context, userID uuid.UUID, messageFeedback *models.MessageFeedback) (*models.MessageFeedback, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, messageFeedbackID uuid.UUID, messageFeedback *models.MessageFeedback, fields *MessageFeedbackUpdateFields) (*models.MessageFeedback, error)
	Delete(ctx context.Context, userID uuid.UUID, messageFeedbackID uuid.UUID) error
}

type MessageFeedbackUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewMessageFeedbackUpdateFields() *MessageFeedbackUpdateFields {
	return &MessageFeedbackUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *MessageFeedbackUpdateFields) MessageID() *MessageFeedbackUpdateFields {
	return f.add("message_id")
}

func (f *MessageFeedbackUpdateFields) ConversationID() *MessageFeedbackUpdateFields {
	return f.add("conversation_id")
}

func (f *MessageFeedbackUpdateFields) Rating() *MessageFeedbackUpdateFields {
	return f.add("rating")
}

func (f *MessageFeedbackUpdateFields) Comment() *MessageFeedbackUpdateFields {
	return f.add("comment")
}

func (f *MessageFeedbackUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *MessageFeedbackUpdateFields) add(column string) *MessageFeedbackUpdateFields {
	if f == nil {
		f = NewMessageFeedbackUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
