// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type ToolConfigRepository interface {
	Create(ctx context.Context, userID uuid.UUID, toolConfig *models.ToolConfig) (*models.ToolConfig, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.ToolConfig, error)
	FindByID(ctx context.Context, userID uuid.UUID, toolConfigID uuid.UUID) (*models.ToolConfig, error)
	Update(ctx context.Context, userID uuid.UUID, toolConfig *models.ToolConfig) (*models.ToolConfig, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, toolConfigID uuid.UUID, toolConfig *models.ToolConfig, fields *ToolConfigUpdateFields) (*models.ToolConfig, error)
	Delete(ctx context.Context, userID uuid.UUID, toolConfigID uuid.UUID) error
}

type ToolConfigUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewToolConfigUpdateFields() *ToolConfigUpdateFields {
	return &ToolConfigUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *ToolConfigUpdateFields) ToolKey() *ToolConfigUpdateFields {
	return f.add("tool_key")
}

func (f *ToolConfigUpdateFields) ToolType() *ToolConfigUpdateFields {
	return f.add("tool_type")
}

func (f *ToolConfigUpdateFields) Enabled() *ToolConfigUpdateFields {
	return f.add("enabled")
}

func (f *ToolConfigUpdateFields) Config() *ToolConfigUpdateFields {
	return f.add("config")
}

func (f *ToolConfigUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *ToolConfigUpdateFields) add(column string) *ToolConfigUpdateFields {
	if f == nil {
		f = NewToolConfigUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
