// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ToolConfigRepository struct {
	db *gorm.DB
}

func NewToolConfigRepository(db *gorm.DB) repository.ToolConfigRepository {
	return &ToolConfigRepository{db: db}
}

func (r *ToolConfigRepository) Create(ctx context.Context, userID uuid.UUID, toolConfig *models.ToolConfig) (*models.ToolConfig, error) {
	toolConfig.UserID = userID
	if err := r.db.WithContext(ctx).Create(toolConfig).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建工具配置失败")
	}
	return toolConfig, nil
}

func (r *ToolConfigRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.ToolConfig, error) {
	var rows []*models.ToolConfig

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询工具配置列表失败")
	}

	return rows, nil
}

func (r *ToolConfigRepository) FindByID(ctx context.Context, userID uuid.UUID, toolConfigID uuid.UUID) (*models.ToolConfig, error) {
	toolConfig := &models.ToolConfig{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", toolConfigID, userID).
		First(toolConfig).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("工具配置不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询工具配置失败")
	}
	return toolConfig, nil
}

func (r *ToolConfigRepository) Update(ctx context.Context, userID uuid.UUID, toolConfig *models.ToolConfig) (*models.ToolConfig, error) {
	result := r.db.WithContext(ctx).
		Model(&models.ToolConfig{}).
		Where("id = ? AND user_id = ?", toolConfig.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(toolConfig)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新工具配置失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("工具配置不存在")
	}
	return r.FindByID(ctx, userID, toolConfig.ID)
}

func (r *ToolConfigRepository) UpdateFields(ctx context.Context, userID uuid.UUID, toolConfigID uuid.UUID, toolConfig *models.ToolConfig, fields *repository.ToolConfigUpdateFields) (*models.ToolConfig, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.ToolConfig{}).
		Where("id = ? AND user_id = ?", toolConfigID, userID).
		Select(columns).
		Updates(toolConfig)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新工具配置失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("工具配置不存在")
	}
	return r.FindByID(ctx, userID, toolConfigID)
}

func (r *ToolConfigRepository) Delete(ctx context.Context, userID uuid.UUID, toolConfigID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", toolConfigID, userID).
		Delete(&models.ToolConfig{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除工具配置失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("工具配置不存在")
	}
	return nil
}
